### ISSUE TITLE
Doesn't include rc info in zip file name

### ISSUE THREAD

**Issue by savvyintegrations** [nRFCloud/package-lambda#10]
I used `npm publish --tag preview` for api-rest-lambdas today and noticed that  CF didn't detect any changes. This, because the zip file uploaded by package-lambda didn't include `-rc.2` in the zip file name (I already had packaged an `rc.1` version:
```
$ SOURCE_REST=$(AWS_PROFILE=nordic_personal npx @nrfcloud/package-lambda local $S3_BUCKET -s node_modules/@nrfcloud/api-rest-lambdas)
Temp dir: /var/folders/pw/xg2lkynj1jxbtdcgj6jv4rqw0000gq/T/tmp-36181jJ9DrsKum7I0
@nrfcloud/api-rest-lambdas 3.7.0-rc.2
running: npm ci --ignore-scripts --only=prod ...
added 414 packages in 6.649s
running: zip -r -q /var/folders/pw/xg2lkynj1jxbtdcgj6jv4rqw0000gq/T/tmp-36181jJ9DrsKum7I0/api-rest-lambdas-3.7.0.zip ./ ...
Uploading to S3: my-cf-lambda-sourcecode/api-rest-lambdas-3.7.0.zip
```
The zip file uploaded to S3 should be my-cf-lambda-sourcecode/api-rest-lambdas-3.7.0-rc.2.zip

**Comment by coderbyheart** [comment]
This is expected since the filename will be constructed using the version in the `package.json`:

https://github.com/nRFCloud/package-lambda/blob/57386a3da7c880936900143a27552eb3d9b4addb/index.js#L84
